Personal Project: Handwritten Digit Recognition

In [ ]:
!pip install pillow mnist numpy sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=dcd999ad0908c84bb6149cc388edf28ea785d25a1786bb4e968b309d527e52f1
  Stored in directory: /root/.cache/pip/wheels/14/25/f7/1cc0956978ae479e75140219088deb7a36f60459df242b1a72
Successfully built sklearn


In [ ]:
from PIL import Image
import mnist
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [ ]:
# training variables
x_train = mnist.train_images()
y_train = mnist.train_labels()

In [ ]:
x_test = mnist.test_images()
y_test = mnist.test_labels()

In [ ]:
print('X_train', x_train) #3 brackets = 3 dimensional
print('X_test', x_test)
print('Y_train', y_train)

X_train [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X_test [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 

In [ ]:
print(x_train.ndim) #confirm how many dimension

3


In [ ]:
print(x_train.shape) #show format #60000 samples data, 28x28 pixels img and changed after reshaped to 784
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [ ]:
x_train = x_train.reshape((-1, 28*28)) #insert -1 later it auto detect the samples data
x_test = x_test.reshape((-1, 28*28))

In [ ]:
print(x_train[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 198 182 247 241   0   0   0   0   

In [ ]:
# to optimize model, scale down data size
x_train = (x_train/256)
x_test = (x_test/256)

In [ ]:
print(x_train[0]) #number changed only ranged between 0 -1 #correct format

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [ ]:
#create model
#adam for large num of data
clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64, 64))
#execute training
clf.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [ ]:
prediction = clf.predict(x_test)

In [ ]:
acc = confusion_matrix(y_test, prediction)

In [ ]:
print(acc) #to know how low our model is #trace/sum

[[ 970    0    0    1    1    0    2    1    5    0]
 [   0 1124    3    2    0    1    2    1    2    0]
 [   5    0 1000    6    4    0    5    4    7    1]
 [   0    0    3  991    0    5    0    4    4    3]
 [   1    0    0    1  962    1    6    1    3    7]
 [   2    0    0    8    0  867    7    2    5    1]
 [   5    3    3    1    4    2  936    0    4    0]
 [   2    4    8    3    1    0    0 1003    4    3]
 [   4    0    2    7    1    2    0    3  951    4]
 [   1    3    0    2    7    3    1    4    6  982]]


In [ ]:
def accuracy(confusion_matrix):
  diagonal = confusion_matrix.trace()
  elements = confusion_matrix.sum()
  return diagonal/elements

In [ ]:
print(accuracy(acc))

0.9786
